package com.example.todoappmvvm.data

import androidx.room.Entity
import androidx.room.PrimaryKey

// List of things that we want to save for each todo items
@Entity
data class Todo(
    val title: String,
    val description: String?,
    val isDone: Boolean,
    // Uniques ID for each items that is generated by room
    @PrimaryKey val id: Int? = null
)
